// Code generated by protoc-gen-go. DO NOT EDIT.
// source: echo.proto

package echosvr

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the str.
type EchoReq struct {
	Str                  string   `protobuf:"bytes,1,opt,name=str" json:"str,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoReq) Reset()         { *m = EchoReq{} }
func (m *EchoReq) String() string { return proto.CompactTextString(m) }
func (*EchoReq) ProtoMessage()    {}
func (*EchoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_echo_e469f208104fbee3, []int{0}
}
func (m *EchoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoReq.Unmarshal(m, b)
}
func (m *EchoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoReq.Marshal(b, m, deterministic)
}
func (dst *EchoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoReq.Merge(dst, src)
}
func (m *EchoReq) XXX_Size() int {
	return xxx_messageInfo_EchoReq.Size(m)
}
func (m *EchoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoReq.DiscardUnknown(m)
}

var xxx_messageInfo_EchoReq proto.InternalMessageInfo

func (m *EchoReq) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

// The response message containing the str
type EchoRsp struct {
	Str                  string   `protobuf:"bytes,1,opt,name=str" json:"str,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoRsp) Reset()         { *m = EchoRsp{} }
func (m *EchoRsp) String() string { return proto.CompactTextString(m) }
func (*EchoRsp) ProtoMessage()    {}
func (*EchoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_echo_e469f208104fbee3, []int{1}
}
func (m *EchoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoRsp.Unmarshal(m, b)
}
func (m *EchoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoRsp.Marshal(b, m, deterministic)
}
func (dst *EchoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoRsp.Merge(dst, src)
}
func (m *EchoRsp) XXX_Size() int {
	return xxx_messageInfo_EchoRsp.Size(m)
}
func (m *EchoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_EchoRsp proto.InternalMessageInfo

func (m *EchoRsp) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

func init() {
	proto.RegisterType((*EchoReq)(nil), "echosvr.EchoReq")
	proto.RegisterType((*EchoRsp)(nil), "echosvr.EchoRsp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EchoSvr service

type EchoSvrClient interface {
	// echo
	Echo(ctx context.Context, in *EchoReq, opts ...grpc.CallOption) (*EchoRsp, error)
}

type echoSvrClient struct {
	cc *grpc.ClientConn
}

func NewEchoSvrClient(cc *grpc.ClientConn) EchoSvrClient {
	return &echoSvrClient{cc}
}

func (c *echoSvrClient) Echo(ctx context.Context, in *EchoReq, opts ...grpc.CallOption) (*EchoRsp, error) {
	out := new(EchoRsp)
	err := grpc.Invoke(ctx, "/echosvr.EchoSvr/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EchoSvr service

type EchoSvrServer interface {
	// echo
	Echo(context.Context, *EchoReq) (*EchoRsp, error)
}

func RegisterEchoSvrServer(s *grpc.Server, srv EchoSvrServer) {
	s.RegisterService(&_EchoSvr_serviceDesc, srv)
}

func _EchoSvr_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoSvrServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/echosvr.EchoSvr/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoSvrServer).Echo(ctx, req.(*EchoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _EchoSvr_serviceDesc = grpc.ServiceDesc{
	ServiceName: "echosvr.EchoSvr",
	HandlerType: (*EchoSvrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _EchoSvr_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "echo.proto",
}

func init() { proto.RegisterFile("echo.proto", fileDescriptor_echo_e469f208104fbee3) }

var fileDescriptor_echo_e469f208104fbee3 = []byte{
	// 109 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4d, 0xce, 0xc8,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x07, 0xb1, 0x8b, 0xcb, 0x8a, 0x94, 0xa4, 0xb9,
	0xd8, 0x5d, 0x93, 0x33, 0xf2, 0x83, 0x52, 0x0b, 0x85, 0x04, 0xb8, 0x98, 0x8b, 0x4b, 0x8a, 0x24,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0xb8, 0x64, 0x71, 0x01, 0xa6, 0xa4, 0x91, 0x39,
	0x44, 0x32, 0xb8, 0xac, 0x48, 0x48, 0x87, 0x8b, 0x05, 0xc4, 0x14, 0x12, 0xd0, 0x83, 0x1a, 0xab,
	0x07, 0x35, 0x53, 0x0a, 0x4d, 0xa4, 0xb8, 0x40, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x04, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x4b, 0xf6, 0xaf, 0x3e, 0x90, 0x00, 0x00, 0x00,
}
