// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package agentsvr

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message
type RouteInfoReq struct {
	SServiceName         string   `protobuf:"bytes,1,opt,name=sServiceName" json:"sServiceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteInfoReq) Reset()         { *m = RouteInfoReq{} }
func (m *RouteInfoReq) String() string { return proto.CompactTextString(m) }
func (*RouteInfoReq) ProtoMessage()    {}
func (*RouteInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_d5856d4c6a44de26, []int{0}
}
func (m *RouteInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteInfoReq.Unmarshal(m, b)
}
func (m *RouteInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteInfoReq.Marshal(b, m, deterministic)
}
func (dst *RouteInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteInfoReq.Merge(dst, src)
}
func (m *RouteInfoReq) XXX_Size() int {
	return xxx_messageInfo_RouteInfoReq.Size(m)
}
func (m *RouteInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_RouteInfoReq proto.InternalMessageInfo

func (m *RouteInfoReq) GetSServiceName() string {
	if m != nil {
		return m.SServiceName
	}
	return ""
}

// The response message
type RouteInfoRsp struct {
	SIp                  string   `protobuf:"bytes,1,opt,name=sIp" json:"sIp,omitempty"`
	IPort                uint32   `protobuf:"varint,2,opt,name=iPort" json:"iPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteInfoRsp) Reset()         { *m = RouteInfoRsp{} }
func (m *RouteInfoRsp) String() string { return proto.CompactTextString(m) }
func (*RouteInfoRsp) ProtoMessage()    {}
func (*RouteInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_d5856d4c6a44de26, []int{1}
}
func (m *RouteInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteInfoRsp.Unmarshal(m, b)
}
func (m *RouteInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteInfoRsp.Marshal(b, m, deterministic)
}
func (dst *RouteInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteInfoRsp.Merge(dst, src)
}
func (m *RouteInfoRsp) XXX_Size() int {
	return xxx_messageInfo_RouteInfoRsp.Size(m)
}
func (m *RouteInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RouteInfoRsp proto.InternalMessageInfo

func (m *RouteInfoRsp) GetSIp() string {
	if m != nil {
		return m.SIp
	}
	return ""
}

func (m *RouteInfoRsp) GetIPort() uint32 {
	if m != nil {
		return m.IPort
	}
	return 0
}

func init() {
	proto.RegisterType((*RouteInfoReq)(nil), "agentsvr.RouteInfoReq")
	proto.RegisterType((*RouteInfoRsp)(nil), "agentsvr.RouteInfoRsp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AgentSvr service

type AgentSvrClient interface {
	// get route info
	GetRouteInfo(ctx context.Context, in *RouteInfoReq, opts ...grpc.CallOption) (*RouteInfoRsp, error)
}

type agentSvrClient struct {
	cc *grpc.ClientConn
}

func NewAgentSvrClient(cc *grpc.ClientConn) AgentSvrClient {
	return &agentSvrClient{cc}
}

func (c *agentSvrClient) GetRouteInfo(ctx context.Context, in *RouteInfoReq, opts ...grpc.CallOption) (*RouteInfoRsp, error) {
	out := new(RouteInfoRsp)
	err := grpc.Invoke(ctx, "/agentsvr.AgentSvr/GetRouteInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AgentSvr service

type AgentSvrServer interface {
	// get route info
	GetRouteInfo(context.Context, *RouteInfoReq) (*RouteInfoRsp, error)
}

func RegisterAgentSvrServer(s *grpc.Server, srv AgentSvrServer) {
	s.RegisterService(&_AgentSvr_serviceDesc, srv)
}

func _AgentSvr_GetRouteInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSvrServer).GetRouteInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agentsvr.AgentSvr/GetRouteInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSvrServer).GetRouteInfo(ctx, req.(*RouteInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AgentSvr_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agentsvr.AgentSvr",
	HandlerType: (*AgentSvrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRouteInfo",
			Handler:    _AgentSvr_GetRouteInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_agent_d5856d4c6a44de26) }

var fileDescriptor_agent_d5856d4c6a44de26 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x4c, 0x4f, 0xcd,
	0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x73, 0x8a, 0xcb, 0x8a, 0x94, 0x8c,
	0xb8, 0x78, 0x82, 0xf2, 0x4b, 0x4b, 0x52, 0x3d, 0xf3, 0xd2, 0xf2, 0x83, 0x52, 0x0b, 0x85, 0x94,
	0xb8, 0x78, 0x8a, 0x83, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0xfd, 0x12, 0x73, 0x53, 0x25, 0x18,
	0x15, 0x18, 0x35, 0x38, 0x83, 0x50, 0xc4, 0x94, 0xcc, 0x90, 0xf5, 0x14, 0x17, 0x08, 0x09, 0x70,
	0x31, 0x17, 0x7b, 0x16, 0x40, 0x95, 0x82, 0x98, 0x42, 0x22, 0x5c, 0xac, 0x99, 0x01, 0xf9, 0x45,
	0x25, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xbc, 0x41, 0x10, 0x8e, 0x91, 0x0f, 0x17, 0x87, 0x23, 0xc8,
	0xde, 0xe0, 0xb2, 0x22, 0x21, 0x07, 0x2e, 0x1e, 0xf7, 0xd4, 0x12, 0xb8, 0x31, 0x42, 0x62, 0x7a,
	0x30, 0x27, 0xe9, 0x21, 0xbb, 0x47, 0x0a, 0xab, 0x78, 0x71, 0x81, 0x12, 0x43, 0x12, 0x1b, 0xd8,
	0x2b, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcb, 0xcb, 0x39, 0xe7, 0xd9, 0x00, 0x00, 0x00,
}
